/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.8.0-rc6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthModeEnum {
    #[serde(rename = "static")]
    Static,
    #[serde(rename = "prompt")]
    Prompt,
}

impl std::fmt::Display for AuthModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Static => write!(f, "static"),
            Self::Prompt => write!(f, "prompt"),
        }
    }
}

impl Default for AuthModeEnum {
    fn default() -> AuthModeEnum {
        Self::Static
    }
}
