/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.0-rc2
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentType {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "app_label")]
    pub app_label: String,
    #[serde(rename = "model")]
    pub model: String,
}

impl ContentType {
    pub fn new(id: i32, app_label: String, model: String) -> ContentType {
        ContentType { id, app_label, model }
    }
}
