/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeliveryMethodEnum {
    #[serde(rename = "https://schemas.openid.net/secevent/risc/delivery-method/push")]
    Push,
    #[serde(rename = "https://schemas.openid.net/secevent/risc/delivery-method/poll")]
    Poll,
}

impl std::fmt::Display for DeliveryMethodEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Push => write!(f, "https://schemas.openid.net/secevent/risc/delivery-method/push"),
            Self::Poll => write!(f, "https://schemas.openid.net/secevent/risc/delivery-method/poll"),
        }
    }
}

impl Default for DeliveryMethodEnum {
    fn default() -> DeliveryMethodEnum {
        Self::Push
    }
}
