/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.8.5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExtraUserObjectPermissionRequest : User permission with additional object-related data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtraUserObjectPermissionRequest {
    #[serde(rename = "object_pk")]
    pub object_pk: String,
}

impl ExtraUserObjectPermissionRequest {
    /// User permission with additional object-related data
    pub fn new(object_pk: String) -> ExtraUserObjectPermissionRequest {
        ExtraUserObjectPermissionRequest { object_pk }
    }
}
