/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.0-rc2
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileList : Base serializer class which doesn't implement create/update methods
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileList {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "mime_type")]
    pub mime_type: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl FileList {
    /// Base serializer class which doesn't implement create/update methods
    pub fn new(name: String, mime_type: String, url: String) -> FileList {
        FileList { name, mime_type, url }
    }
}
