/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.8.0-rc7
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InitialPermissionsModeEnum {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "role")]
    Role,
}

impl std::fmt::Display for InitialPermissionsModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::User => write!(f, "user"),
            Self::Role => write!(f, "role"),
        }
    }
}

impl Default for InitialPermissionsModeEnum {
    fn default() -> InitialPermissionsModeEnum {
        Self::User
    }
}
