/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.10.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KadminTypeEnum {
    #[serde(rename = "MIT")]
    Mit,
    #[serde(rename = "Heimdal")]
    Heimdal,
    #[serde(rename = "other")]
    Other,
}

impl std::fmt::Display for KadminTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Mit => write!(f, "MIT"),
            Self::Heimdal => write!(f, "Heimdal"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for KadminTypeEnum {
    fn default() -> KadminTypeEnum {
        Self::Mit
    }
}
