/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.6.4
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModelEnum {
    #[serde(rename = "authentik_tenants.domain")]
    AuthentikTenantsPeriodDomain,
    #[serde(rename = "authentik_crypto.certificatekeypair")]
    AuthentikCryptoPeriodCertificatekeypair,
    #[serde(rename = "authentik_events.event")]
    AuthentikEventsPeriodEvent,
    #[serde(rename = "authentik_events.notificationtransport")]
    AuthentikEventsPeriodNotificationtransport,
    #[serde(rename = "authentik_events.notification")]
    AuthentikEventsPeriodNotification,
    #[serde(rename = "authentik_events.notificationrule")]
    AuthentikEventsPeriodNotificationrule,
    #[serde(rename = "authentik_events.notificationwebhookmapping")]
    AuthentikEventsPeriodNotificationwebhookmapping,
    #[serde(rename = "authentik_flows.flow")]
    AuthentikFlowsPeriodFlow,
    #[serde(rename = "authentik_flows.flowstagebinding")]
    AuthentikFlowsPeriodFlowstagebinding,
    #[serde(rename = "authentik_outposts.dockerserviceconnection")]
    AuthentikOutpostsPeriodDockerserviceconnection,
    #[serde(rename = "authentik_outposts.kubernetesserviceconnection")]
    AuthentikOutpostsPeriodKubernetesserviceconnection,
    #[serde(rename = "authentik_outposts.outpost")]
    AuthentikOutpostsPeriodOutpost,
    #[serde(rename = "authentik_policies_dummy.dummypolicy")]
    AuthentikPoliciesDummyPeriodDummypolicy,
    #[serde(rename = "authentik_policies_event_matcher.eventmatcherpolicy")]
    AuthentikPoliciesEventMatcherPeriodEventmatcherpolicy,
    #[serde(rename = "authentik_policies_expiry.passwordexpirypolicy")]
    AuthentikPoliciesExpiryPeriodPasswordexpirypolicy,
    #[serde(rename = "authentik_policies_expression.expressionpolicy")]
    AuthentikPoliciesExpressionPeriodExpressionpolicy,
    #[serde(rename = "authentik_policies_geoip.geoippolicy")]
    AuthentikPoliciesGeoipPeriodGeoippolicy,
    #[serde(rename = "authentik_policies_password.passwordpolicy")]
    AuthentikPoliciesPasswordPeriodPasswordpolicy,
    #[serde(rename = "authentik_policies_reputation.reputationpolicy")]
    AuthentikPoliciesReputationPeriodReputationpolicy,
    #[serde(rename = "authentik_policies.policybinding")]
    AuthentikPoliciesPeriodPolicybinding,
    #[serde(rename = "authentik_providers_ldap.ldapprovider")]
    AuthentikProvidersLdapPeriodLdapprovider,
    #[serde(rename = "authentik_providers_oauth2.scopemapping")]
    AuthentikProvidersOauth2PeriodScopemapping,
    #[serde(rename = "authentik_providers_oauth2.oauth2provider")]
    AuthentikProvidersOauth2PeriodOauth2provider,
    #[serde(rename = "authentik_providers_proxy.proxyprovider")]
    AuthentikProvidersProxyPeriodProxyprovider,
    #[serde(rename = "authentik_providers_rac.racprovider")]
    AuthentikProvidersRacPeriodRacprovider,
    #[serde(rename = "authentik_providers_rac.endpoint")]
    AuthentikProvidersRacPeriodEndpoint,
    #[serde(rename = "authentik_providers_rac.racpropertymapping")]
    AuthentikProvidersRacPeriodRacpropertymapping,
    #[serde(rename = "authentik_providers_radius.radiusprovider")]
    AuthentikProvidersRadiusPeriodRadiusprovider,
    #[serde(rename = "authentik_providers_radius.radiusproviderpropertymapping")]
    AuthentikProvidersRadiusPeriodRadiusproviderpropertymapping,
    #[serde(rename = "authentik_providers_saml.samlprovider")]
    AuthentikProvidersSamlPeriodSamlprovider,
    #[serde(rename = "authentik_providers_saml.samlpropertymapping")]
    AuthentikProvidersSamlPeriodSamlpropertymapping,
    #[serde(rename = "authentik_providers_scim.scimprovider")]
    AuthentikProvidersScimPeriodScimprovider,
    #[serde(rename = "authentik_providers_scim.scimmapping")]
    AuthentikProvidersScimPeriodScimmapping,
    #[serde(rename = "authentik_rbac.role")]
    AuthentikRbacPeriodRole,
    #[serde(rename = "authentik_rbac.initialpermissions")]
    AuthentikRbacPeriodInitialpermissions,
    #[serde(rename = "authentik_sources_kerberos.kerberossource")]
    AuthentikSourcesKerberosPeriodKerberossource,
    #[serde(rename = "authentik_sources_kerberos.kerberossourcepropertymapping")]
    AuthentikSourcesKerberosPeriodKerberossourcepropertymapping,
    #[serde(rename = "authentik_sources_kerberos.userkerberossourceconnection")]
    AuthentikSourcesKerberosPeriodUserkerberossourceconnection,
    #[serde(rename = "authentik_sources_kerberos.groupkerberossourceconnection")]
    AuthentikSourcesKerberosPeriodGroupkerberossourceconnection,
    #[serde(rename = "authentik_sources_ldap.ldapsource")]
    AuthentikSourcesLdapPeriodLdapsource,
    #[serde(rename = "authentik_sources_ldap.ldapsourcepropertymapping")]
    AuthentikSourcesLdapPeriodLdapsourcepropertymapping,
    #[serde(rename = "authentik_sources_ldap.userldapsourceconnection")]
    AuthentikSourcesLdapPeriodUserldapsourceconnection,
    #[serde(rename = "authentik_sources_ldap.groupldapsourceconnection")]
    AuthentikSourcesLdapPeriodGroupldapsourceconnection,
    #[serde(rename = "authentik_sources_oauth.oauthsource")]
    AuthentikSourcesOauthPeriodOauthsource,
    #[serde(rename = "authentik_sources_oauth.oauthsourcepropertymapping")]
    AuthentikSourcesOauthPeriodOauthsourcepropertymapping,
    #[serde(rename = "authentik_sources_oauth.useroauthsourceconnection")]
    AuthentikSourcesOauthPeriodUseroauthsourceconnection,
    #[serde(rename = "authentik_sources_oauth.groupoauthsourceconnection")]
    AuthentikSourcesOauthPeriodGroupoauthsourceconnection,
    #[serde(rename = "authentik_sources_plex.plexsource")]
    AuthentikSourcesPlexPeriodPlexsource,
    #[serde(rename = "authentik_sources_plex.plexsourcepropertymapping")]
    AuthentikSourcesPlexPeriodPlexsourcepropertymapping,
    #[serde(rename = "authentik_sources_plex.userplexsourceconnection")]
    AuthentikSourcesPlexPeriodUserplexsourceconnection,
    #[serde(rename = "authentik_sources_plex.groupplexsourceconnection")]
    AuthentikSourcesPlexPeriodGroupplexsourceconnection,
    #[serde(rename = "authentik_sources_saml.samlsource")]
    AuthentikSourcesSamlPeriodSamlsource,
    #[serde(rename = "authentik_sources_saml.samlsourcepropertymapping")]
    AuthentikSourcesSamlPeriodSamlsourcepropertymapping,
    #[serde(rename = "authentik_sources_saml.usersamlsourceconnection")]
    AuthentikSourcesSamlPeriodUsersamlsourceconnection,
    #[serde(rename = "authentik_sources_saml.groupsamlsourceconnection")]
    AuthentikSourcesSamlPeriodGroupsamlsourceconnection,
    #[serde(rename = "authentik_sources_scim.scimsource")]
    AuthentikSourcesScimPeriodScimsource,
    #[serde(rename = "authentik_sources_scim.scimsourcepropertymapping")]
    AuthentikSourcesScimPeriodScimsourcepropertymapping,
    #[serde(rename = "authentik_stages_authenticator_duo.authenticatorduostage")]
    AuthentikStagesAuthenticatorDuoPeriodAuthenticatorduostage,
    #[serde(rename = "authentik_stages_authenticator_duo.duodevice")]
    AuthentikStagesAuthenticatorDuoPeriodDuodevice,
    #[serde(rename = "authentik_stages_authenticator_email.authenticatoremailstage")]
    AuthentikStagesAuthenticatorEmailPeriodAuthenticatoremailstage,
    #[serde(rename = "authentik_stages_authenticator_email.emaildevice")]
    AuthentikStagesAuthenticatorEmailPeriodEmaildevice,
    #[serde(rename = "authentik_stages_authenticator_sms.authenticatorsmsstage")]
    AuthentikStagesAuthenticatorSmsPeriodAuthenticatorsmsstage,
    #[serde(rename = "authentik_stages_authenticator_sms.smsdevice")]
    AuthentikStagesAuthenticatorSmsPeriodSmsdevice,
    #[serde(rename = "authentik_stages_authenticator_static.authenticatorstaticstage")]
    AuthentikStagesAuthenticatorStaticPeriodAuthenticatorstaticstage,
    #[serde(rename = "authentik_stages_authenticator_static.staticdevice")]
    AuthentikStagesAuthenticatorStaticPeriodStaticdevice,
    #[serde(rename = "authentik_stages_authenticator_totp.authenticatortotpstage")]
    AuthentikStagesAuthenticatorTotpPeriodAuthenticatortotpstage,
    #[serde(rename = "authentik_stages_authenticator_totp.totpdevice")]
    AuthentikStagesAuthenticatorTotpPeriodTotpdevice,
    #[serde(rename = "authentik_stages_authenticator_validate.authenticatorvalidatestage")]
    AuthentikStagesAuthenticatorValidatePeriodAuthenticatorvalidatestage,
    #[serde(rename = "authentik_stages_authenticator_webauthn.authenticatorwebauthnstage")]
    AuthentikStagesAuthenticatorWebauthnPeriodAuthenticatorwebauthnstage,
    #[serde(rename = "authentik_stages_authenticator_webauthn.webauthndevice")]
    AuthentikStagesAuthenticatorWebauthnPeriodWebauthndevice,
    #[serde(rename = "authentik_stages_captcha.captchastage")]
    AuthentikStagesCaptchaPeriodCaptchastage,
    #[serde(rename = "authentik_stages_consent.consentstage")]
    AuthentikStagesConsentPeriodConsentstage,
    #[serde(rename = "authentik_stages_consent.userconsent")]
    AuthentikStagesConsentPeriodUserconsent,
    #[serde(rename = "authentik_stages_deny.denystage")]
    AuthentikStagesDenyPeriodDenystage,
    #[serde(rename = "authentik_stages_dummy.dummystage")]
    AuthentikStagesDummyPeriodDummystage,
    #[serde(rename = "authentik_stages_email.emailstage")]
    AuthentikStagesEmailPeriodEmailstage,
    #[serde(rename = "authentik_stages_identification.identificationstage")]
    AuthentikStagesIdentificationPeriodIdentificationstage,
    #[serde(rename = "authentik_stages_invitation.invitationstage")]
    AuthentikStagesInvitationPeriodInvitationstage,
    #[serde(rename = "authentik_stages_invitation.invitation")]
    AuthentikStagesInvitationPeriodInvitation,
    #[serde(rename = "authentik_stages_password.passwordstage")]
    AuthentikStagesPasswordPeriodPasswordstage,
    #[serde(rename = "authentik_stages_prompt.prompt")]
    AuthentikStagesPromptPeriodPrompt,
    #[serde(rename = "authentik_stages_prompt.promptstage")]
    AuthentikStagesPromptPeriodPromptstage,
    #[serde(rename = "authentik_stages_redirect.redirectstage")]
    AuthentikStagesRedirectPeriodRedirectstage,
    #[serde(rename = "authentik_stages_user_delete.userdeletestage")]
    AuthentikStagesUserDeletePeriodUserdeletestage,
    #[serde(rename = "authentik_stages_user_login.userloginstage")]
    AuthentikStagesUserLoginPeriodUserloginstage,
    #[serde(rename = "authentik_stages_user_logout.userlogoutstage")]
    AuthentikStagesUserLogoutPeriodUserlogoutstage,
    #[serde(rename = "authentik_stages_user_write.userwritestage")]
    AuthentikStagesUserWritePeriodUserwritestage,
    #[serde(rename = "authentik_tasks_schedules.schedule")]
    AuthentikTasksSchedulesPeriodSchedule,
    #[serde(rename = "authentik_brands.brand")]
    AuthentikBrandsPeriodBrand,
    #[serde(rename = "authentik_blueprints.blueprintinstance")]
    AuthentikBlueprintsPeriodBlueprintinstance,
    #[serde(rename = "authentik_core.group")]
    AuthentikCorePeriodGroup,
    #[serde(rename = "authentik_core.user")]
    AuthentikCorePeriodUser,
    #[serde(rename = "authentik_core.application")]
    AuthentikCorePeriodApplication,
    #[serde(rename = "authentik_core.applicationentitlement")]
    AuthentikCorePeriodApplicationentitlement,
    #[serde(rename = "authentik_core.token")]
    AuthentikCorePeriodToken,
    #[serde(rename = "authentik_enterprise.license")]
    AuthentikEnterprisePeriodLicense,
    #[serde(rename = "authentik_policies_unique_password.uniquepasswordpolicy")]
    AuthentikPoliciesUniquePasswordPeriodUniquepasswordpolicy,
    #[serde(rename = "authentik_providers_google_workspace.googleworkspaceprovider")]
    AuthentikProvidersGoogleWorkspacePeriodGoogleworkspaceprovider,
    #[serde(rename = "authentik_providers_google_workspace.googleworkspaceprovidermapping")]
    AuthentikProvidersGoogleWorkspacePeriodGoogleworkspaceprovidermapping,
    #[serde(rename = "authentik_providers_microsoft_entra.microsoftentraprovider")]
    AuthentikProvidersMicrosoftEntraPeriodMicrosoftentraprovider,
    #[serde(rename = "authentik_providers_microsoft_entra.microsoftentraprovidermapping")]
    AuthentikProvidersMicrosoftEntraPeriodMicrosoftentraprovidermapping,
    #[serde(rename = "authentik_providers_ssf.ssfprovider")]
    AuthentikProvidersSsfPeriodSsfprovider,
    #[serde(rename = "authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage")]
    AuthentikStagesAuthenticatorEndpointGdtcPeriodAuthenticatorendpointgdtcstage,
    #[serde(rename = "authentik_stages_mtls.mutualtlsstage")]
    AuthentikStagesMtlsPeriodMutualtlsstage,
    #[serde(rename = "authentik_stages_source.sourcestage")]
    AuthentikStagesSourcePeriodSourcestage,
}

impl std::fmt::Display for ModelEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AuthentikTenantsPeriodDomain => write!(f, "authentik_tenants.domain"),
            Self::AuthentikCryptoPeriodCertificatekeypair => write!(f, "authentik_crypto.certificatekeypair"),
            Self::AuthentikEventsPeriodEvent => write!(f, "authentik_events.event"),
            Self::AuthentikEventsPeriodNotificationtransport => write!(f, "authentik_events.notificationtransport"),
            Self::AuthentikEventsPeriodNotification => write!(f, "authentik_events.notification"),
            Self::AuthentikEventsPeriodNotificationrule => write!(f, "authentik_events.notificationrule"),
            Self::AuthentikEventsPeriodNotificationwebhookmapping => {
                write!(f, "authentik_events.notificationwebhookmapping")
            }
            Self::AuthentikFlowsPeriodFlow => write!(f, "authentik_flows.flow"),
            Self::AuthentikFlowsPeriodFlowstagebinding => write!(f, "authentik_flows.flowstagebinding"),
            Self::AuthentikOutpostsPeriodDockerserviceconnection => {
                write!(f, "authentik_outposts.dockerserviceconnection")
            }
            Self::AuthentikOutpostsPeriodKubernetesserviceconnection => {
                write!(f, "authentik_outposts.kubernetesserviceconnection")
            }
            Self::AuthentikOutpostsPeriodOutpost => write!(f, "authentik_outposts.outpost"),
            Self::AuthentikPoliciesDummyPeriodDummypolicy => write!(f, "authentik_policies_dummy.dummypolicy"),
            Self::AuthentikPoliciesEventMatcherPeriodEventmatcherpolicy => {
                write!(f, "authentik_policies_event_matcher.eventmatcherpolicy")
            }
            Self::AuthentikPoliciesExpiryPeriodPasswordexpirypolicy => {
                write!(f, "authentik_policies_expiry.passwordexpirypolicy")
            }
            Self::AuthentikPoliciesExpressionPeriodExpressionpolicy => {
                write!(f, "authentik_policies_expression.expressionpolicy")
            }
            Self::AuthentikPoliciesGeoipPeriodGeoippolicy => write!(f, "authentik_policies_geoip.geoippolicy"),
            Self::AuthentikPoliciesPasswordPeriodPasswordpolicy => {
                write!(f, "authentik_policies_password.passwordpolicy")
            }
            Self::AuthentikPoliciesReputationPeriodReputationpolicy => {
                write!(f, "authentik_policies_reputation.reputationpolicy")
            }
            Self::AuthentikPoliciesPeriodPolicybinding => write!(f, "authentik_policies.policybinding"),
            Self::AuthentikProvidersLdapPeriodLdapprovider => write!(f, "authentik_providers_ldap.ldapprovider"),
            Self::AuthentikProvidersOauth2PeriodScopemapping => write!(f, "authentik_providers_oauth2.scopemapping"),
            Self::AuthentikProvidersOauth2PeriodOauth2provider => {
                write!(f, "authentik_providers_oauth2.oauth2provider")
            }
            Self::AuthentikProvidersProxyPeriodProxyprovider => write!(f, "authentik_providers_proxy.proxyprovider"),
            Self::AuthentikProvidersRacPeriodRacprovider => write!(f, "authentik_providers_rac.racprovider"),
            Self::AuthentikProvidersRacPeriodEndpoint => write!(f, "authentik_providers_rac.endpoint"),
            Self::AuthentikProvidersRacPeriodRacpropertymapping => {
                write!(f, "authentik_providers_rac.racpropertymapping")
            }
            Self::AuthentikProvidersRadiusPeriodRadiusprovider => {
                write!(f, "authentik_providers_radius.radiusprovider")
            }
            Self::AuthentikProvidersRadiusPeriodRadiusproviderpropertymapping => {
                write!(f, "authentik_providers_radius.radiusproviderpropertymapping")
            }
            Self::AuthentikProvidersSamlPeriodSamlprovider => write!(f, "authentik_providers_saml.samlprovider"),
            Self::AuthentikProvidersSamlPeriodSamlpropertymapping => {
                write!(f, "authentik_providers_saml.samlpropertymapping")
            }
            Self::AuthentikProvidersScimPeriodScimprovider => write!(f, "authentik_providers_scim.scimprovider"),
            Self::AuthentikProvidersScimPeriodScimmapping => write!(f, "authentik_providers_scim.scimmapping"),
            Self::AuthentikRbacPeriodRole => write!(f, "authentik_rbac.role"),
            Self::AuthentikRbacPeriodInitialpermissions => write!(f, "authentik_rbac.initialpermissions"),
            Self::AuthentikSourcesKerberosPeriodKerberossource => {
                write!(f, "authentik_sources_kerberos.kerberossource")
            }
            Self::AuthentikSourcesKerberosPeriodKerberossourcepropertymapping => {
                write!(f, "authentik_sources_kerberos.kerberossourcepropertymapping")
            }
            Self::AuthentikSourcesKerberosPeriodUserkerberossourceconnection => {
                write!(f, "authentik_sources_kerberos.userkerberossourceconnection")
            }
            Self::AuthentikSourcesKerberosPeriodGroupkerberossourceconnection => {
                write!(f, "authentik_sources_kerberos.groupkerberossourceconnection")
            }
            Self::AuthentikSourcesLdapPeriodLdapsource => write!(f, "authentik_sources_ldap.ldapsource"),
            Self::AuthentikSourcesLdapPeriodLdapsourcepropertymapping => {
                write!(f, "authentik_sources_ldap.ldapsourcepropertymapping")
            }
            Self::AuthentikSourcesLdapPeriodUserldapsourceconnection => {
                write!(f, "authentik_sources_ldap.userldapsourceconnection")
            }
            Self::AuthentikSourcesLdapPeriodGroupldapsourceconnection => {
                write!(f, "authentik_sources_ldap.groupldapsourceconnection")
            }
            Self::AuthentikSourcesOauthPeriodOauthsource => write!(f, "authentik_sources_oauth.oauthsource"),
            Self::AuthentikSourcesOauthPeriodOauthsourcepropertymapping => {
                write!(f, "authentik_sources_oauth.oauthsourcepropertymapping")
            }
            Self::AuthentikSourcesOauthPeriodUseroauthsourceconnection => {
                write!(f, "authentik_sources_oauth.useroauthsourceconnection")
            }
            Self::AuthentikSourcesOauthPeriodGroupoauthsourceconnection => {
                write!(f, "authentik_sources_oauth.groupoauthsourceconnection")
            }
            Self::AuthentikSourcesPlexPeriodPlexsource => write!(f, "authentik_sources_plex.plexsource"),
            Self::AuthentikSourcesPlexPeriodPlexsourcepropertymapping => {
                write!(f, "authentik_sources_plex.plexsourcepropertymapping")
            }
            Self::AuthentikSourcesPlexPeriodUserplexsourceconnection => {
                write!(f, "authentik_sources_plex.userplexsourceconnection")
            }
            Self::AuthentikSourcesPlexPeriodGroupplexsourceconnection => {
                write!(f, "authentik_sources_plex.groupplexsourceconnection")
            }
            Self::AuthentikSourcesSamlPeriodSamlsource => write!(f, "authentik_sources_saml.samlsource"),
            Self::AuthentikSourcesSamlPeriodSamlsourcepropertymapping => {
                write!(f, "authentik_sources_saml.samlsourcepropertymapping")
            }
            Self::AuthentikSourcesSamlPeriodUsersamlsourceconnection => {
                write!(f, "authentik_sources_saml.usersamlsourceconnection")
            }
            Self::AuthentikSourcesSamlPeriodGroupsamlsourceconnection => {
                write!(f, "authentik_sources_saml.groupsamlsourceconnection")
            }
            Self::AuthentikSourcesScimPeriodScimsource => write!(f, "authentik_sources_scim.scimsource"),
            Self::AuthentikSourcesScimPeriodScimsourcepropertymapping => {
                write!(f, "authentik_sources_scim.scimsourcepropertymapping")
            }
            Self::AuthentikStagesAuthenticatorDuoPeriodAuthenticatorduostage => {
                write!(f, "authentik_stages_authenticator_duo.authenticatorduostage")
            }
            Self::AuthentikStagesAuthenticatorDuoPeriodDuodevice => {
                write!(f, "authentik_stages_authenticator_duo.duodevice")
            }
            Self::AuthentikStagesAuthenticatorEmailPeriodAuthenticatoremailstage => {
                write!(f, "authentik_stages_authenticator_email.authenticatoremailstage")
            }
            Self::AuthentikStagesAuthenticatorEmailPeriodEmaildevice => {
                write!(f, "authentik_stages_authenticator_email.emaildevice")
            }
            Self::AuthentikStagesAuthenticatorSmsPeriodAuthenticatorsmsstage => {
                write!(f, "authentik_stages_authenticator_sms.authenticatorsmsstage")
            }
            Self::AuthentikStagesAuthenticatorSmsPeriodSmsdevice => {
                write!(f, "authentik_stages_authenticator_sms.smsdevice")
            }
            Self::AuthentikStagesAuthenticatorStaticPeriodAuthenticatorstaticstage => {
                write!(f, "authentik_stages_authenticator_static.authenticatorstaticstage")
            }
            Self::AuthentikStagesAuthenticatorStaticPeriodStaticdevice => {
                write!(f, "authentik_stages_authenticator_static.staticdevice")
            }
            Self::AuthentikStagesAuthenticatorTotpPeriodAuthenticatortotpstage => {
                write!(f, "authentik_stages_authenticator_totp.authenticatortotpstage")
            }
            Self::AuthentikStagesAuthenticatorTotpPeriodTotpdevice => {
                write!(f, "authentik_stages_authenticator_totp.totpdevice")
            }
            Self::AuthentikStagesAuthenticatorValidatePeriodAuthenticatorvalidatestage => {
                write!(f, "authentik_stages_authenticator_validate.authenticatorvalidatestage")
            }
            Self::AuthentikStagesAuthenticatorWebauthnPeriodAuthenticatorwebauthnstage => {
                write!(f, "authentik_stages_authenticator_webauthn.authenticatorwebauthnstage")
            }
            Self::AuthentikStagesAuthenticatorWebauthnPeriodWebauthndevice => {
                write!(f, "authentik_stages_authenticator_webauthn.webauthndevice")
            }
            Self::AuthentikStagesCaptchaPeriodCaptchastage => write!(f, "authentik_stages_captcha.captchastage"),
            Self::AuthentikStagesConsentPeriodConsentstage => write!(f, "authentik_stages_consent.consentstage"),
            Self::AuthentikStagesConsentPeriodUserconsent => write!(f, "authentik_stages_consent.userconsent"),
            Self::AuthentikStagesDenyPeriodDenystage => write!(f, "authentik_stages_deny.denystage"),
            Self::AuthentikStagesDummyPeriodDummystage => write!(f, "authentik_stages_dummy.dummystage"),
            Self::AuthentikStagesEmailPeriodEmailstage => write!(f, "authentik_stages_email.emailstage"),
            Self::AuthentikStagesIdentificationPeriodIdentificationstage => {
                write!(f, "authentik_stages_identification.identificationstage")
            }
            Self::AuthentikStagesInvitationPeriodInvitationstage => {
                write!(f, "authentik_stages_invitation.invitationstage")
            }
            Self::AuthentikStagesInvitationPeriodInvitation => write!(f, "authentik_stages_invitation.invitation"),
            Self::AuthentikStagesPasswordPeriodPasswordstage => write!(f, "authentik_stages_password.passwordstage"),
            Self::AuthentikStagesPromptPeriodPrompt => write!(f, "authentik_stages_prompt.prompt"),
            Self::AuthentikStagesPromptPeriodPromptstage => write!(f, "authentik_stages_prompt.promptstage"),
            Self::AuthentikStagesRedirectPeriodRedirectstage => write!(f, "authentik_stages_redirect.redirectstage"),
            Self::AuthentikStagesUserDeletePeriodUserdeletestage => {
                write!(f, "authentik_stages_user_delete.userdeletestage")
            }
            Self::AuthentikStagesUserLoginPeriodUserloginstage => {
                write!(f, "authentik_stages_user_login.userloginstage")
            }
            Self::AuthentikStagesUserLogoutPeriodUserlogoutstage => {
                write!(f, "authentik_stages_user_logout.userlogoutstage")
            }
            Self::AuthentikStagesUserWritePeriodUserwritestage => {
                write!(f, "authentik_stages_user_write.userwritestage")
            }
            Self::AuthentikTasksSchedulesPeriodSchedule => write!(f, "authentik_tasks_schedules.schedule"),
            Self::AuthentikBrandsPeriodBrand => write!(f, "authentik_brands.brand"),
            Self::AuthentikBlueprintsPeriodBlueprintinstance => write!(f, "authentik_blueprints.blueprintinstance"),
            Self::AuthentikCorePeriodGroup => write!(f, "authentik_core.group"),
            Self::AuthentikCorePeriodUser => write!(f, "authentik_core.user"),
            Self::AuthentikCorePeriodApplication => write!(f, "authentik_core.application"),
            Self::AuthentikCorePeriodApplicationentitlement => write!(f, "authentik_core.applicationentitlement"),
            Self::AuthentikCorePeriodToken => write!(f, "authentik_core.token"),
            Self::AuthentikEnterprisePeriodLicense => write!(f, "authentik_enterprise.license"),
            Self::AuthentikPoliciesUniquePasswordPeriodUniquepasswordpolicy => {
                write!(f, "authentik_policies_unique_password.uniquepasswordpolicy")
            }
            Self::AuthentikProvidersGoogleWorkspacePeriodGoogleworkspaceprovider => {
                write!(f, "authentik_providers_google_workspace.googleworkspaceprovider")
            }
            Self::AuthentikProvidersGoogleWorkspacePeriodGoogleworkspaceprovidermapping => {
                write!(f, "authentik_providers_google_workspace.googleworkspaceprovidermapping")
            }
            Self::AuthentikProvidersMicrosoftEntraPeriodMicrosoftentraprovider => {
                write!(f, "authentik_providers_microsoft_entra.microsoftentraprovider")
            }
            Self::AuthentikProvidersMicrosoftEntraPeriodMicrosoftentraprovidermapping => {
                write!(f, "authentik_providers_microsoft_entra.microsoftentraprovidermapping")
            }
            Self::AuthentikProvidersSsfPeriodSsfprovider => write!(f, "authentik_providers_ssf.ssfprovider"),
            Self::AuthentikStagesAuthenticatorEndpointGdtcPeriodAuthenticatorendpointgdtcstage => write!(
                f,
                "authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage"
            ),
            Self::AuthentikStagesMtlsPeriodMutualtlsstage => write!(f, "authentik_stages_mtls.mutualtlsstage"),
            Self::AuthentikStagesSourcePeriodSourcestage => write!(f, "authentik_stages_source.sourcestage"),
        }
    }
}

impl Default for ModelEnum {
    fn default() -> ModelEnum {
        Self::AuthentikTenantsPeriodDomain
    }
}
