/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.8.0-rc7
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MutualTlsStageModeEnum {
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "required")]
    Required,
}

impl std::fmt::Display for MutualTlsStageModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Optional => write!(f, "optional"),
            Self::Required => write!(f, "required"),
        }
    }
}

impl Default for MutualTlsStageModeEnum {
    fn default() -> MutualTlsStageModeEnum {
        Self::Optional
    }
}
