/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.6.4
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NameIdPolicyEnum {
    #[serde(rename = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress")]
    UrnColonOasisColonNamesColonTcColonSamlColon1Period1ColonNameidFormatColonEmailAddress,
    #[serde(rename = "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent")]
    UrnColonOasisColonNamesColonTcColonSamlColon2Period0ColonNameidFormatColonPersistent,
    #[serde(rename = "urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName")]
    UrnColonOasisColonNamesColonTcColonSamlColon1Period1ColonNameidFormatColonX509SubjectName,
    #[serde(rename = "urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName")]
    UrnColonOasisColonNamesColonTcColonSamlColon2Period0ColonNameidFormatColonWindowsDomainQualifiedName,
    #[serde(rename = "urn:oasis:names:tc:SAML:2.0:nameid-format:transient")]
    UrnColonOasisColonNamesColonTcColonSamlColon2Period0ColonNameidFormatColonTransient,
}

impl std::fmt::Display for NameIdPolicyEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UrnColonOasisColonNamesColonTcColonSamlColon1Period1ColonNameidFormatColonEmailAddress => write!(f, "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"),
            Self::UrnColonOasisColonNamesColonTcColonSamlColon2Period0ColonNameidFormatColonPersistent => write!(f, "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"),
            Self::UrnColonOasisColonNamesColonTcColonSamlColon1Period1ColonNameidFormatColonX509SubjectName => write!(f, "urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName"),
            Self::UrnColonOasisColonNamesColonTcColonSamlColon2Period0ColonNameidFormatColonWindowsDomainQualifiedName => write!(f, "urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName"),
            Self::UrnColonOasisColonNamesColonTcColonSamlColon2Period0ColonNameidFormatColonTransient => write!(f, "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"),
        }
    }
}

impl Default for NameIdPolicyEnum {
    fn default() -> NameIdPolicyEnum {
        Self::UrnColonOasisColonNamesColonTcColonSamlColon1Period1ColonNameidFormatColonEmailAddress
    }
}
