/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.2.0
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedOAuth2ProviderList {
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
    #[serde(rename = "results")]
    pub results: Vec<models::OAuth2Provider>,
}

impl PaginatedOAuth2ProviderList {
    pub fn new(pagination: models::Pagination, results: Vec<models::OAuth2Provider>) -> PaginatedOAuth2ProviderList {
        PaginatedOAuth2ProviderList { pagination, results }
    }
}
