/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.10.0-rc3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedSettingsRequestFlags {
    #[serde(rename = "policies_buffered_access_view")]
    pub policies_buffered_access_view: bool,
}

impl PatchedSettingsRequestFlags {
    pub fn new(policies_buffered_access_view: bool) -> PatchedSettingsRequestFlags {
        PatchedSettingsRequestFlags {
            policies_buffered_access_view,
        }
    }
}
