/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.6.2
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedApplicationEntitlementRequest : ApplicationEntitlement Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedApplicationEntitlementRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<uuid::Uuid>,
    #[serde(
        rename = "attributes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attributes: Option<Option<serde_json::Value>>,
}

impl PatchedApplicationEntitlementRequest {
    /// ApplicationEntitlement Serializer
    pub fn new() -> PatchedApplicationEntitlementRequest {
        PatchedApplicationEntitlementRequest {
            name: None,
            app: None,
            attributes: None,
        }
    }
}
