/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.8.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedUserSamlSourceConnectionRequest : SAML Source Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedUserSamlSourceConnectionRequest {
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
}

impl PatchedUserSamlSourceConnectionRequest {
    /// SAML Source Serializer
    pub fn new() -> PatchedUserSamlSourceConnectionRequest {
        PatchedUserSamlSourceConnectionRequest { identifier: None }
    }
}
