/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.8.5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PermissionRequest : Global permission
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "codename")]
    pub codename: String,
}

impl PermissionRequest {
    /// Global permission
    pub fn new(name: String, codename: String) -> PermissionRequest {
        PermissionRequest { name, codename }
    }
}
