/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.6.4
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProviderModelEnum {
    #[serde(rename = "authentik_providers_google_workspace.googleworkspaceprovider")]
    AuthentikProvidersGoogleWorkspacePeriodGoogleworkspaceprovider,
    #[serde(rename = "authentik_providers_ldap.ldapprovider")]
    AuthentikProvidersLdapPeriodLdapprovider,
    #[serde(rename = "authentik_providers_microsoft_entra.microsoftentraprovider")]
    AuthentikProvidersMicrosoftEntraPeriodMicrosoftentraprovider,
    #[serde(rename = "authentik_providers_oauth2.oauth2provider")]
    AuthentikProvidersOauth2PeriodOauth2provider,
    #[serde(rename = "authentik_providers_proxy.proxyprovider")]
    AuthentikProvidersProxyPeriodProxyprovider,
    #[serde(rename = "authentik_providers_rac.racprovider")]
    AuthentikProvidersRacPeriodRacprovider,
    #[serde(rename = "authentik_providers_radius.radiusprovider")]
    AuthentikProvidersRadiusPeriodRadiusprovider,
    #[serde(rename = "authentik_providers_saml.samlprovider")]
    AuthentikProvidersSamlPeriodSamlprovider,
    #[serde(rename = "authentik_providers_scim.scimprovider")]
    AuthentikProvidersScimPeriodScimprovider,
    #[serde(rename = "authentik_providers_ssf.ssfprovider")]
    AuthentikProvidersSsfPeriodSsfprovider,
}

impl std::fmt::Display for ProviderModelEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AuthentikProvidersGoogleWorkspacePeriodGoogleworkspaceprovider => {
                write!(f, "authentik_providers_google_workspace.googleworkspaceprovider")
            }
            Self::AuthentikProvidersLdapPeriodLdapprovider => write!(f, "authentik_providers_ldap.ldapprovider"),
            Self::AuthentikProvidersMicrosoftEntraPeriodMicrosoftentraprovider => {
                write!(f, "authentik_providers_microsoft_entra.microsoftentraprovider")
            }
            Self::AuthentikProvidersOauth2PeriodOauth2provider => {
                write!(f, "authentik_providers_oauth2.oauth2provider")
            }
            Self::AuthentikProvidersProxyPeriodProxyprovider => write!(f, "authentik_providers_proxy.proxyprovider"),
            Self::AuthentikProvidersRacPeriodRacprovider => write!(f, "authentik_providers_rac.racprovider"),
            Self::AuthentikProvidersRadiusPeriodRadiusprovider => {
                write!(f, "authentik_providers_radius.radiusprovider")
            }
            Self::AuthentikProvidersSamlPeriodSamlprovider => write!(f, "authentik_providers_saml.samlprovider"),
            Self::AuthentikProvidersScimPeriodScimprovider => write!(f, "authentik_providers_scim.scimprovider"),
            Self::AuthentikProvidersSsfPeriodSsfprovider => write!(f, "authentik_providers_ssf.ssfprovider"),
        }
    }
}

impl Default for ProviderModelEnum {
    fn default() -> ProviderModelEnum {
        Self::AuthentikProvidersGoogleWorkspacePeriodGoogleworkspaceprovider
    }
}
