/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.10.0
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScimSourceUserRequest : SCIMSourceUser Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScimSourceUserRequest {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "user")]
    pub user: i32,
    #[serde(rename = "source")]
    pub source: uuid::Uuid,
    #[serde(
        rename = "attributes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attributes: Option<Option<serde_json::Value>>,
}

impl ScimSourceUserRequest {
    /// SCIMSourceUser Serializer
    pub fn new(id: String, user: i32, source: uuid::Uuid) -> ScimSourceUserRequest {
        ScimSourceUserRequest {
            id,
            user,
            source,
            attributes: None,
        }
    }
}
