/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.12.2
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScimSourceGroupRequest : SCIMSourceGroup Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScimSourceGroupRequest {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "group")]
    pub group: uuid::Uuid,
    #[serde(rename = "source")]
    pub source: uuid::Uuid,
    #[serde(
        rename = "attributes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attributes: Option<Option<serde_json::Value>>,
}

impl ScimSourceGroupRequest {
    /// SCIMSourceGroup Serializer
    pub fn new(id: String, group: uuid::Uuid, source: uuid::Uuid) -> ScimSourceGroupRequest {
        ScimSourceGroupRequest {
            id,
            group,
            source,
            attributes: None,
        }
    }
}
