/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.8.5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SourceStageRequest : SourceStage Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceStageRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "flow_set", skip_serializing_if = "Option::is_none")]
    pub flow_set: Option<Vec<models::FlowSetRequest>>,
    #[serde(rename = "source")]
    pub source: uuid::Uuid,
    /// Amount of time a user can take to return from the source to continue the flow (Format: hours=-1;minutes=-2;seconds=-3)
    #[serde(rename = "resume_timeout", skip_serializing_if = "Option::is_none")]
    pub resume_timeout: Option<String>,
}

impl SourceStageRequest {
    /// SourceStage Serializer
    pub fn new(name: String, source: uuid::Uuid) -> SourceStageRequest {
        SourceStageRequest {
            name,
            flow_set: None,
            source,
            resume_timeout: None,
        }
    }
}
