/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.10.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StateEnum {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "consumed")]
    Consumed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "done")]
    Done,
}

impl std::fmt::Display for StateEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Queued => write!(f, "queued"),
            Self::Consumed => write!(f, "consumed"),
            Self::Rejected => write!(f, "rejected"),
            Self::Done => write!(f, "done"),
        }
    }
}

impl Default for StateEnum {
    fn default() -> StateEnum {
        Self::Queued
    }
}
