/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.10.4
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SyncStatus : Provider sync status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncStatus {
    #[serde(rename = "is_running")]
    pub is_running: bool,
    #[serde(rename = "tasks")]
    pub tasks: Vec<models::SystemTask>,
}

impl SyncStatus {
    /// Provider sync status
    pub fn new(is_running: bool, tasks: Vec<models::SystemTask>) -> SyncStatus {
        SyncStatus { is_running, tasks }
    }
}
