/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.2.2
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserKerberosSourceConnectionRequest : Kerberos Source Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserKerberosSourceConnectionRequest {
    #[serde(rename = "user")]
    pub user: i32,
    #[serde(rename = "source")]
    pub source: uuid::Uuid,
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl UserKerberosSourceConnectionRequest {
    /// Kerberos Source Serializer
    pub fn new(user: i32, source: uuid::Uuid, identifier: String) -> UserKerberosSourceConnectionRequest {
        UserKerberosSourceConnectionRequest {
            user,
            source,
            identifier,
        }
    }
}
