/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.10.5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSamlSourceConnectionRequest : SAML Source Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSamlSourceConnectionRequest {
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl UserSamlSourceConnectionRequest {
    /// SAML Source Serializer
    pub fn new(identifier: String) -> UserSamlSourceConnectionRequest {
        UserSamlSourceConnectionRequest { identifier }
    }
}
