/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.8.4
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebAuthnDeviceTypeRequest : WebAuthnDeviceType Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebAuthnDeviceTypeRequest {
    #[serde(rename = "aaguid")]
    pub aaguid: uuid::Uuid,
    #[serde(rename = "description")]
    pub description: String,
}

impl WebAuthnDeviceTypeRequest {
    /// WebAuthnDeviceType Serializer
    pub fn new(aaguid: uuid::Uuid, description: String) -> WebAuthnDeviceTypeRequest {
        WebAuthnDeviceTypeRequest { aaguid, description }
    }
}
