---
name: Rolling release

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - id: get-user-id
        name: Get GitHub app user ID
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: "${{ steps.app-token.outputs.token }}"
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Check for updates
        run: make version=main
      - name: Push
        id: push
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          RUSTFLAGS: -Awarnings
        run: |
          git restore Cargo.toml
          git diff --exit-code >/dev/null && exit 0 || echo
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          version=$(cd version && cargo run)
          sed -i -e "s/^version.*/version = \"${version}\"/" Cargo.toml
          git add .
          git commit -F "diff.test" || exit 0
          git tag v$version
          git push
          git push --tags
          cargo publish
          truncate -s '<125000' diff.test
          gh release create v$version -F diff.test --prerelease
